src/Models/OverviewViewModel.cs
using TandemBooking.Models;
using System.Collections.Generic;

namespace TandemBooking.Models
{
    public class OverviewViewModel
    {
        public List<Booking> UpcomingBookings { get; set; }
        public List<Booking> MissingPilotBookings { get; set; }
        public List<Booking> RecentBookings { get; set; }
        public List<Booking> CorrespondingBookings { get; set; }
    }
}

src/Controllers/OverviewController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TandemBooking.Models;
using Microsoft.EntityFrameworkCore;
using TandemBooking.Services;

namespace TandemBooking.Controllers
{

    [Authorize(Policy="IsValidated")]
    public class OverviewController : Controller
    {
        private readonly TandemBookingContext _context;
        private readonly UserManager _userManager;
        private readonly BookingService _bookingService;
        private readonly MessageService _messageService;

        public OverviewController(TandemBookingContext context, BookingService bookingService,
            MessageService messageService, UserManager userManager)
        {
            _context = context;
            _bookingService = bookingService;
            _messageService = messageService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var result = new OverviewViewModel();
            if (User.IsPilot())
            {
                result.MissingPilotBookings = _context.Bookings
                    .Include(b => b.AssignedPilot)
                    .AsNoTracking()
                    .Where(b => !b.Canceled && b.BookingDate >= DateTime.Today)
                    .Where(b => b.AssignedPilot == null)
                    .OrderBy(b => b.BookingDate).ThenBy(b => b.TimeSlot).ThenBy(b => b.DateRegistered)
                    .ToList();

                result.CorrespondingBookings = _context.Bookings
                    .Include(b => b.AssignedPilot)
                    .AsNoTracking()
                    .Where(b => !b.Canceled)
                    .Where(b => b.AssignedPilot != null)
                    .Where(b => b.AssignedPilotId != _userManager.GetUserId(User))
                    .ToList();

                result.UpcomingBookings = _context.Bookings
                    .Include(b => b.AssignedPilot)
                    .AsNoTracking()
                    .Where(b => !b.Canceled && b.BookingDate >= DateTime.Today)
                    .Where(b => b.AssignedPilotId == _userManager.GetUserId(User))
                    .OrderBy(b => b.BookingDate).ThenBy(b => b.TimeSlot).ThenBy(b => b.DateRegistered)
                    .ToList();

                result.RecentBookings = _context.Bookings
                    .Include(b => b.AssignedPilot)
                    .AsNoTracking()
                    .Where(b => !b.Canceled && b.BookingDate < DateTime.Today)
                    .Where(b => b.AssignedPilotId == _userManager.GetUserId(User))
                    .OrderByDescending(b => b.BookingDate).ThenBy(b => b.DateRegistered)
                    .Take(10)
                    .ToList();

            }

            return View(result);
        }

        [HttpGet]
        public async Task<ActionResult> AssignMe(Guid id)
        {
            var booking = await _context.Bookings
                .Include(b => b.AssignedPilot)
                .Include(b => b.BookingEvents)
                .FirstOrDefaultAsync(b => b.Id == id);
            var userId = _userManager.GetUserId(User);
            var pilot = _context.Users.Single(u => u.Id == userId);
            _bookingService.AssignNewPilot(booking, pilot);
            _context.SaveChanges();
            var bookingDateString = booking.BookingDate.ToString("dd.MM.yyyy") + " at " + booking.TimeSlot.asTime();
            await _messageService.SendNewPilotMessage(bookingDateString, booking, true);
            return RedirectToAction("");
        }

    }
}

src/Controllers/ReportController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TandemBooking.Models;
using Microsoft.EntityFrameworkCore;
using TandemBooking.Services;

namespace TandemBooking.Controllers
{
    [Authorize(Policy = "IsValidated")]
    public class ReportController : Controller
    {
        private readonly TandemBookingContext _context;
        private readonly UserManager _userManager;

        public ReportController(TandemBookingContext context, UserManager userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> CompletedBookings(string pilotId = null, int? year = null)
        {
            var fromDate = new DateTime(year ?? DateTime.Today.Year, 1, 1);
            var toDate = fromDate.AddYears(1);
            if (toDate > DateTime.Today)
            {
                toDate = DateTime.Today;
            }

            var bookings = _context.Bookings
                .Include(b => b.AssignedPilot)
                .AsNoTracking()
                .Where(b => !b.Canceled && b.BookingDate >= fromDate && b.BookingDate < toDate);

            //Pilots should be able to see their own flights
            if (!User.IsAdmin())
            {
                pilotId = _userManager.GetUserId(User);
            }

            if (pilotId != null)
            {
                bookings = bookings.Where(b => b.AssignedPilot.Id == pilotId);
            }

            var pilotName = pilotId == null
                ? "all pilots"
                : (await _userManager.FindByIdAsync(pilotId)).Name;

            var orderedBookings = bookings
                .OrderBy(b => b.BookingDate)
                .ToList();

            return View(new CompletedBookingsViewModel()
            {
                Bookings = orderedBookings,
                Year = fromDate.Year,
                PilotId = pilotId,
                PilotName = pilotName
            });
        }

        [Authorize(Policy = "IsAdmin")]
        public IActionResult BookingsByPilot(int? year = null)
        {
            var fromDate = new DateTime(year ?? DateTime.Today.Year, 1, 1);
            var toDate = fromDate.AddYears(1);
            if (toDate > DateTime.Today)
            {
                toDate = DateTime.Today;
            }

            var pilots = _context.Users.ToList();

            var basicQuery = _context.Bookings
                .AsNoTracking()
                .Where(b => !b.Canceled && b.AssignedPilotId != null && b.BookingDate >= fromDate && b.BookingDate < toDate);

            var pilotStats = _context.Bookings
                .AsNoTracking()
                .Where(b => !b.Canceled && b.AssignedPilotId != null && b.BookingDate >= fromDate && b.BookingDate < toDate)
                .Where(b => b.PassengerFee > 0)
                .GroupBy(b => b.AssignedPilotId)
                .Select(grp => new BookingsByPilotViewModelItem
                {
                    PilotId = grp.Key,
                    PilotName = pilots.First(p => p.Id == grp.Key).Name,
                    CompletedFlights = grp.Count(b => b.Completed),
                    FlightsMissingStatus = grp.Count(b => !b.Completed),
                })
                .ToList()
                .OrderByDescending(b => b.CompletedFlights + b.FlightsMissingStatus)
                .ToList();

            return View(new BookingsByPilotViewModel()
            {
                Year = fromDate.Year,
                PilotStats = pilotStats,
            });
        }



        public async Task<IActionResult> MyCompletedBookings(string pilotId = null, DateTime? fromDate = null, DateTime? toDate = null)
        {
            if (fromDate == null)
                fromDate = DateTime.Today.AddMonths(-1);
            if (toDate == null)
                toDate = DateTime.Today;
            

            var bookings = _context.Bookings
                .Include(b => b.AssignedPilot)
                .AsNoTracking()
                .Where(b => !b.Canceled && b.BookingDate >= fromDate && b.BookingDate < toDate);

            pilotId = _userManager.GetUserId(User);
        
            if (pilotId != null)
            {
                bookings = bookings.Where(b => b.AssignedPilot.Id == pilotId);
            }

            var pilotName = pilotId == null
                ? "all pilots"
                : (await _userManager.FindByIdAsync(pilotId)).Name;

            var orderedBookings = bookings
                .OrderBy(b => b.BookingDate)
                .ToList();

            return View(new CompletedBookingsViewModel()
            {
                Bookings = orderedBookings,
                Year = fromDate.Value.Year,
                FromDate = fromDate,
                ToDate = toDate,
                PilotId = pilotId,
                PilotName = pilotName
            });
        }
    }
}

src/Views/Overview/Index.cshtml
@using TandemBooking.Services
@model TandemBooking.Models.OverviewViewModel
@{
    ViewData["Title"] = $"Booking Overview";
}

<div class="clearfix">
    <ul class="nav navbar-nav">
        <li class=""><a href="@Url.Action("Create", "BookingAdmin")">New Booking</a></li>
        <li><a href="@Url.Action("Index", "BookingAdmin")">All Bookings</a></li>
        <li><a href="@Url.Action("MyCompletedBookings", "Report")">My bookings</a></li>
        @if (User.IsAdmin())
        {
            <li><a href="@Url.Action("CompletedBookings", "Report")">All Completed bookings</a></li>
            <li><a href="@Url.Action("BookingsByPilot", "Report")">Completed bookings per pilot</a></li>
        }
    </ul>
</div>

@if (Model.MissingPilotBookings != null)
{
    <h2>Bookings Without Pilot</h2>

    @if (Model.MissingPilotBookings.Count() > 0) 
    {
        DateTime current_date = new DateTime();

    <table class="table">
        <tr>
            <th>Date</th>
            <th>Time</th>
            <th>Passenger</th>
            <th>Weight</th>
        </tr>
        @foreach (var booking in Model.MissingPilotBookings)
        {
            if (booking.BookingDate != current_date)
            {
                current_date = booking.BookingDate;
        <tr class="active">
            <td>@booking.BookingDate.ToString("dd.MM.yyyy")</td>
            <td></td>
            <td></td>
            <td></td>
            @{ 
                int count_others = Model.CorrespondingBookings
                .Where(b => b.BookingDate == booking.BookingDate)
                .Count();
                if (count_others > 0)
                {
                    <td class="text-right"><button class="btn btn-default" onclick="show_other_flights('@current_date.ToString("ddMMyyyy")')">Other flights</button></td>
                }
                else { <td></td>}
            }
        </tr>
                foreach (var other_booking in Model.CorrespondingBookings
                    .Where(b => b.BookingDate == booking.BookingDate)
                    .OrderBy(b => b.TimeSlot)
                        .ToList())
                    {
                        <tr class="hidden active @current_date.ToString("ddMMyyyy")">
                            <td></td>
                            <td>@other_booking.TimeSlot.asTime()</td>
                            <td>@other_booking.AssignedPilot?.Name</td>
                            <td>@other_booking.PassengerWeight.AsWeight()</td>

                            <td class="text-right">
                                <a href="@Url.Action("Details", "BookingAdmin" , new { id=other_booking.Id })" class="btn btn-default">Details</a>

                            </td>

                        </tr>
                    }
                }
            <tr>

                <td></td>
                <td>@booking.TimeSlot.asTime()</td>
                <td>
                    @booking.PassengerName
                </td>
                <td>
                    @booking.PassengerWeight.AsWeight()
                </td>
                <td class="text-right">
                    <a href="@Url.Action("AssignMe", "Overview" , new { id=booking.Id })" class="btn btn-success">Assign Me</a>
                    <a href="@Url.Action("Details", "BookingAdmin" , new { id=booking.Id })" class="btn btn-default">Details</a>
                </td>
            </tr>
        }
    </table>
    }
    else
    {
        <p>No upcoming bookings without pilots</p>
    }
}

@if (Model.UpcomingBookings != null)
{
    <h2>My Upcoming Bookings</h2>

    @if (Model.UpcomingBookings.Count() > 0)
    {
        <table class="table">
            <tr>
                <th>Date</th>
                <th>Time</th>
                <th>Passenger</th>
                <th></th>
            </tr>
            @foreach (var booking in Model.UpcomingBookings)
            {
            <tr>
                <td>@booking.BookingDate.ToString("dd.MM.yyyy")</td>
                <td>@booking.TimeSlot.asTime()</td>
                <td>@booking.PassengerName</td>
                <td class="text-right">
                    <a href="@Url.Action("Details", "BookingAdmin", new { id = booking.Id })" class="btn btn-default">Details</a>
                    @if (!booking.Canceled && !booking.Completed)
        {
            <a href="@Url.Action("Cancel", "BookingAdmin", new { id = booking.Id })" class="btn btn-danger">Cancel</a>
}
                </td>
            </tr>
            }
        </table>
    }
    else
    {
        <p>You do not have any upcoming bookings</p>
    }
}

@if (Model.RecentBookings != null)
{
    <h2>My Recent Bookings</h2>

    @if (Model.RecentBookings.Count() > 0)
    {
        <table class="table">
            <tr>
                <th>Date</th>
                <th>Time</th>
                <th>Passenger</th>
                <th></th>
            </tr>
            @foreach (var booking in Model.RecentBookings)
            {
            <tr>
                <td>@booking.BookingDate.ToString("dd.MM.yyyy")</td>
                <td>@booking.TimeSlot.asTime()</td>
                <td>@booking.PassengerName</td>
                <td class="text-right">
                    <a href="@Url.Action("Details", "BookingAdmin", new { id = booking.Id })" class="btn btn-sm btn-default">Details</a>
                    @if (!booking.Canceled && !booking.Completed)
        {
            <a href="@Url.Action("Cancel", "BookingAdmin", new { id = booking.Id })" class="btn btn-sm btn-danger">Cancel</a>
            <a href="@Url.Action("Complete", "BookingAdmin", new { id = booking.Id })" class="btn btn-sm btn-success">Complete</a>
}
                </td>
            </tr>
            }
        </table>
    }
    else
    {
        <p>No recent bookings found</p>
    }
}

<script>
    function show_other_flights(id) {
        var other_flights = document.getElementsByClassName(id);
        for (var i = 0; i < other_flights.length; i++) {
            other_flights[i].classList.toggle("hidden");
        }
    }
</script>