src/ViewModels/BookingAdmin/AssignPilotPostbackModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TandemBooking.ViewModels.BookingAdmin
{
    public class AssignPilotPostbackModel
    {
        public string NewPilotMessage { get; set; }
        public string NewPilotUserId { get; set; }
        public bool NewPilotNotifyPassenger { get; set; }
    }
}

src/ViewModels/BookingAdmin/BookingAssignPilotViewModel.cs
using System.Collections.Generic;
using TandemBooking.Models;
using TandemBooking.Services;

namespace TandemBooking.ViewModels.BookingAdmin
{
    public class BookingAssignPilotViewModel
    {
        public string ErrorMessage { get; set; }
        public TandemBooking.Models.Booking Booking { get; set; }
        public List<AvailablePilot> AvailablePilots { get; set; }
    }
}

src/ViewModels/BookingAdmin/BookingCancelViewModel.cs
using System.Collections.Generic;
using TandemBooking.Models;
using TandemBooking.Services;

namespace TandemBooking.ViewModels.BookingAdmin
{
    public class BookingCancelViewModel
    {
        public string ErrorMessage { get; set; }
        public TandemBooking.Models.Booking Booking { get; set; }
    }
}

src/ViewModels/BookingAdmin/BookingDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TandemBooking.Services;

namespace TandemBooking.ViewModels.BookingAdmin
{
    public class BookingDetailsViewModel
    {
        public string ErrorMessage { get; set; }
        public Models.Booking Booking { get; set; } 
        public List<AvailablePilot> AvailablePilots { get; set; }
        public bool Editable { get; set; }
    }
}
    

src/ViewModels/BookingAdmin/BookingEditViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TandemBooking.ViewModels.BookingAdmin
{
    public class EditBookingViewModel
    {
        public Guid Id { get; set; }

        [Required]
        public DateTime BookingDate { get; set; }
        public string PassengerName { get; set; }
        public int? PassengerWeight { get; set; }
        public string PassengerEmail { get; set; }
        public string PassengerPhone { get; set; }
        public int PassengerFee { get; set; }

        public int TimeSlot { get; set; }

    }
}

src/ViewModels/BookingAdmin/CancelBookingPostbackModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TandemBooking.ViewModels.BookingAdmin
{
    public class CancelBookingPostbackModel
    {
        public string CancelMessage { get; set; }
        public bool NotifyPassenger { get; set; }
    }
}

src/Controllers/BookingAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.WebSockets;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TandemBooking.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using TandemBooking.Services;
using TandemBooking.ViewModels.BookingAdmin;

namespace TandemBooking.Controllers
{
    [Authorize(Policy = "IsValidated")]
    public class BookingAdminController : Controller
    {
        private readonly ILogger<BookingAdminController> _logger;
        private readonly TandemBookingContext _context;
        private readonly BookingService _bookingService;
        private readonly MessageService _messageService;
        private readonly BookingCoordinatorSettings _bookingCoordinatorSettings;
        private readonly UserManager _userManager;
        private readonly INexmoService _nexmo;

        public BookingAdminController(TandemBookingContext context, INexmoService nexmo, BookingService bookingService,
            MessageService messageService, BookingCoordinatorSettings bookingCoordinatorSettings,
            UserManager userManager, ILogger<BookingAdminController> logger)
        {
            _context = context;
            _bookingService = bookingService;
            _messageService = messageService;
            _bookingCoordinatorSettings = bookingCoordinatorSettings;
            _userManager = userManager;
            _logger = logger;
            _nexmo = nexmo;
        }

        #region List Bookings

        public ActionResult Index(string userId = null)
        {
            var bookingQuery = _context.Bookings
                .Include(b => b.AssignedPilot)
                .Where(u => u.BookingDate >= DateTime.UtcNow.AddDays(-30))
                .OrderByDescending(u => u.BookingDate).ThenBy(u => u.DateRegistered)
                .AsQueryable();

            //non-admin users can only see their own bookings
            if (userId != null)
            {
                bookingQuery = bookingQuery.Where(b => b.AssignedPilot.Id == userId);
            }

            //get at least 30 bookings and all bookings from the last 30days
            var bookings = bookingQuery
                .AsEnumerable()
                .TakeWhile((booking, index) => booking.BookingDate > DateTime.Now.AddDays(-30) || index < 30)
                .ToList();

            return View(bookings);
        }

        #endregion

        #region Create New Booking

        [HttpGet]
        public ActionResult Create(Guid? cloneBookingId = null)
        {
            CreateBookingViewModel vm;
            if (cloneBookingId.HasValue)
            {
                var originalBooking = _context.Bookings
                    .FirstOrDefault(b => b.Id == cloneBookingId);
                if (originalBooking == null)
                {
                    return NotFound();
                }

                vm = new CreateBookingViewModel
                {
                    Date = originalBooking.BookingDate,
                    TimeSlot = originalBooking.TimeSlot,
                    Email = originalBooking.PassengerEmail,
                    PhoneNumber = originalBooking.PassengerPhone.AsPhoneNumber(),
                    Name = originalBooking.PassengerName + " +1",
                    Weight = originalBooking.PassengerWeight,
                    Comment = originalBooking.Comment,
                    PrimaryBookingId = originalBooking.Id,
                    NotifyPassenger = false,
                    NotifyPilot = true,
                    PassengerFee = (int)originalBooking.PassengerFee,
                };
            }
            else
            {
                vm = new CreateBookingViewModel
                {
                    Date = DateTime.Today,
                };
            }

            return View(vm);
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateBookingViewModel input)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (input.Date == null)
                    {
                        ModelState.AddModelError("Date", "Please select a date");
                        return View(input);
                    }

                    //if phone number is provided, make sure it is valid. 
                    //if no phone number is provided, that's ok as well
                    string phoneNumber = null;
                    if (!string.IsNullOrEmpty(input.PhoneNumber))
                    {
                        phoneNumber = await _nexmo.FormatPhoneNumber(input.PhoneNumber);
                        if (phoneNumber == null)
                        {
                            ModelState.AddModelError("PhoneNumber", "Please enter a valid phone number");
                            return View(input);
                        }
                    }

                    //Fetch primary booking if this is a clone
                    Booking primaryBooking = null;
                    if (input.PrimaryBookingId != null)
                    {
                        primaryBooking = _context.Bookings
                            .FirstOrDefault(b => b.Id == input.PrimaryBookingId);
                    }

                    //create booking
                    var booking = new Booking()
                    {
                        BookingDate = input.Date.Value.Date,
                        TimeSlot = input.TimeSlot,
                        DateRegistered = DateTime.UtcNow,
                        PassengerEmail = input.Email,
                        PassengerName = input.Name,
                        PassengerWeight = input.Weight,
                        PassengerPhone = phoneNumber,
                        Comment = input.Comment,
                        BookingEvents = new List<BookingEvent>(),
                        PrimaryBooking = primaryBooking,
                        PassengerFee = input.PassengerFee,
                    };
                    _context.Add(booking);

                    //assign pilot
                    if (string.IsNullOrEmpty(input.PilotId))
                    {
                        //if no pilot is selected, find a new one
                        await _bookingService.AssignNewPilotAsync(booking);
                    }
                    else
                    {
                        //or use pilot as provided
                        var pilot = await _userManager.FindByIdAsync(input.PilotId);
                        _bookingService.AssignNewPilot(booking, pilot);
                    }
                    _context.SaveChanges();

                    await _messageService.SendNewBookingMessage(booking, new Booking[] {}, input.NotifyPassenger, input.NotifyPilot);

                    //redirect to edit action
                    return RedirectToAction("Details", new {id = booking.Id});
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(0, $"Error creating booking, {ex.Message}, {ex}");
                ModelState.AddModelError("", $"An unexpected error occured during booking, please contact the booking coordinator, {_bookingCoordinatorSettings.Name}, on {_bookingCoordinatorSettings.PhoneNumber}");
            }

            return View(input);
        }

        public ActionResult PilotSelector(string controlName, DateTime date)
        {
            return ViewComponent("PilotSelector", new {controlName, date});
        }

        #endregion

        #region Edit Booking

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var booking = _context.Bookings
                .FirstOrDefault(b => b.Id == id);
            if (booking == null)
            {
                return NotFound();
            }

            var vm = new EditBookingViewModel
            {
                Id = booking.Id,
                BookingDate = booking.BookingDate,
                TimeSlot = booking.TimeSlot,
                PassengerName = booking.PassengerName,
                PassengerWeight = booking.PassengerWeight,
                PassengerEmail = booking.PassengerEmail,
                PassengerPhone = booking.PassengerPhone.AsPhoneNumber(),
                PassengerFee = (int)booking.PassengerFee,
            };
            return View(vm);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(Guid id, EditBookingViewModel input)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //if phone number is provided, make sure it is valid. 
                    //if no phone number is provided, that's ok as well
                    string phoneNumber = null;
                    if (!string.IsNullOrEmpty(input.PassengerPhone))
                    {
                        phoneNumber = await _nexmo.FormatPhoneNumber(input.PassengerPhone);
                        if (phoneNumber == null)
                        {
                            ModelState.AddModelError("PassengerPhone", "Please enter a valid phone number");
                            return View(input);
                        }
                    }

                    var booking = _context.Bookings
                        .Include(b => b.AssignedPilot)
                        .FirstOrDefault(b => b.Id == id);
                    if (booking == null)
                    {
                        return NotFound();
                    }

                    var userId = _userManager.GetUserId(User);
                    if (!User.IsAdmin() && booking.AssignedPilot.Id != userId)
                    {
                        return RedirectToAction("Details", new { id = id, errorMessage = "Only admin or currently assigned pilot can edit booking" });
                    }

src/Controllers/ReportController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TandemBooking.Models;
using Microsoft.EntityFrameworkCore;
using TandemBooking.Services;

namespace TandemBooking.Controllers
{
    [Authorize(Policy = "IsValidated")]
    public class ReportController : Controller
    {
        private readonly TandemBookingContext _context;
        private readonly UserManager _userManager;

        public ReportController(TandemBookingContext context, UserManager userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> CompletedBookings(string pilotId = null, int? year = null)
        {
            var fromDate = new DateTime(year ?? DateTime.Today.Year, 1, 1);
            var toDate = fromDate.AddYears(1);
            if (toDate > DateTime.Today)
            {
                toDate = DateTime.Today;
            }

            var bookings = _context.Bookings
                .Include(b => b.AssignedPilot)
                .AsNoTracking()
                .Where(b => !b.Canceled && b.BookingDate >= fromDate && b.BookingDate < toDate);

            //Pilots should be able to see their own flights
            if (!User.IsAdmin())
            {
                pilotId = _userManager.GetUserId(User);
            }

            if (pilotId != null)
            {
                bookings = bookings.Where(b => b.AssignedPilot.Id == pilotId);
            }

            var pilotName = pilotId == null
                ? "all pilots"
                : (await _userManager.FindByIdAsync(pilotId)).Name;

            var orderedBookings = bookings
                .OrderBy(b => b.BookingDate)
                .ToList();

            return View(new CompletedBookingsViewModel()
            {
                Bookings = orderedBookings,
                Year = fromDate.Year,
                PilotId = pilotId,
                PilotName = pilotName
            });
        }

        [Authorize(Policy = "IsAdmin")]
        public IActionResult BookingsByPilot(int? year = null)
        {
            var fromDate = new DateTime(year ?? DateTime.Today.Year, 1, 1);
            var toDate = fromDate.AddYears(1);
            if (toDate > DateTime.Today)
            {
                toDate = DateTime.Today;
            }

            var pilots = _context.Users.ToList();

            var basicQuery = _context.Bookings
                .AsNoTracking()
                .Where(b => !b.Canceled && b.AssignedPilotId != null && b.BookingDate >= fromDate && b.BookingDate < toDate);

            var pilotStats = _context.Bookings
                .AsNoTracking()
                .Where(b => !b.Canceled && b.AssignedPilotId != null && b.BookingDate >= fromDate && b.BookingDate < toDate)
                .Where(b => b.PassengerFee > 0)
                .GroupBy(b => b.AssignedPilotId)
                .Select(grp => new BookingsByPilotViewModelItem
                {
                    PilotId = grp.Key,
                    PilotName = pilots.First(p => p.Id == grp.Key).Name,
                    CompletedFlights = grp.Count(b => b.Completed),
                    FlightsMissingStatus = grp.Count(b => !b.Completed),
                })
                .ToList()
                .OrderByDescending(b => b.CompletedFlights + b.FlightsMissingStatus)
                .ToList();

            return View(new BookingsByPilotViewModel()
            {
                Year = fromDate.Year,
                PilotStats = pilotStats,
            });
        }



        public async Task<IActionResult> MyCompletedBookings(string pilotId = null, DateTime? fromDate = null, DateTime? toDate = null)
        {
            if (fromDate == null)
                fromDate = DateTime.Today.AddMonths(-1);
            if (toDate == null)
                toDate = DateTime.Today;
            

            var bookings = _context.Bookings
                .Include(b => b.AssignedPilot)
                .AsNoTracking()
                .Where(b => !b.Canceled && b.BookingDate >= fromDate && b.BookingDate < toDate);

            pilotId = _userManager.GetUserId(User);
        
            if (pilotId != null)
            {
                bookings = bookings.Where(b => b.AssignedPilot.Id == pilotId);
            }

            var pilotName = pilotId == null
                ? "all pilots"
                : (await _userManager.FindByIdAsync(pilotId)).Name;

            var orderedBookings = bookings
                .OrderBy(b => b.BookingDate)
                .ToList();

            return View(new CompletedBookingsViewModel()
            {
                Bookings = orderedBookings,
                Year = fromDate.Value.Year,
                FromDate = fromDate,
                ToDate = toDate,
                PilotId = pilotId,
                PilotName = pilotName
            });
        }
    }
}

src/Views/BookingAdmin/AssignPilot.cshtml
@using TandemBooking.Services
@model TandemBooking.ViewModels.BookingAdmin.BookingAssignPilotViewModel
@{
    ViewData["Title"] = "Assign new pilot";
}

<h2>@ViewData["Title"]</h2>

@if (Model.ErrorMessage != null)
{
    <div class="alert alert-danger">@Model.ErrorMessage</div>
}

<div class="row">
    <div class="col-sm-12">
        <section>
            <div class="col-sm-12">
                <p>If the currently assign pilot is unable to make the flight, use this to find a new pilot from the available pilots to take the flight. A message is sent to the passenger notifying him of the new pilot. If no other pilots are available, the tandem coordinator is notified and tasked with finding a new pilot.</p>
                <form asp-controller="BookingAdmin" asp-action="AssignPilot" method="post" role="form" onsubmit="return submitNewPilot()">
                    <input type="hidden" name="Id" value="@Model.Booking.Id"/>
                    <div class="form-group">
                        <textarea class="form-control" id="NewPilotMessage" name="NewPilotMessage" placeholder="Please enter a reason to assign a new pilot"></textarea>
                    </div>

                    <p>
                        Select "Choose from available pilots" to make a fair selection of pilot based on priority. If no pilots are available, you can use this dropdown to select a pilot not marked as available (Remember to verify that the pilot can actually make the flight first).
                    </p>
                    <div class="form-group">
                        <select class="form-control" id="NewPilotUserId" name="NewPilotUserId" placeholder="Please enter a reason to assign a new pilot">
                            <option value="">Choose from available pilots</option>
                            @foreach (var pilot in Model.AvailablePilots.OrderByDescending(p => p.Available).ThenBy(p => p.Priority))
                            {
                                <option class="@(pilot.Available ? "available" : "unavailable")" value="@pilot.Pilot.Id">
                                    @pilot.Pilot.Name (@pilot.Pilot.PhoneNumber.AsPhoneNumber())
                                    @pilot.Pilot.FormatWeightRange()
                                    @(pilot.Available ? "Available" : "Unavailable"),
                                    Priority @(pilot.Priority)
                                </option>
                            }
                        </select>
                    </div>

                    <p>
                        You can uncheck the "send message to passenger" checkbox if you are changing the pilot after the flight was performed in order to make the booking reflect reality (i.e. another pilot got the flight in the end). 
                    </p>
                    <div class="form-group">
                        <div class="checkbox checkbox-inline">
                            <input type="checkbox" name="NewPilotNotifyPassenger" id="NewPilotNotifyPassenger" value="true" checked="checked" />
                            <label class="control-label" for="NewPilotNotifyPassenger">
                                Send message to passenger via SMS
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-info">Assign new pilot</button>
                    </div>
                </form>
            </div>
        </section>

        <div>
            <a href="@Url.Action("Details", new { id = Model.Booking.Id })">Back to Booking Details</a>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        function submitNewPilot() {
            return confirm("Unassign the current pilot and find a new one?")
        }
    </script>
}

src/Views/BookingAdmin/Cancel.cshtml
@using TandemBooking.Services
@model TandemBooking.ViewModels.BookingAdmin.BookingCancelViewModel
@{
    ViewData["Title"] = "Cancel Booking";
}

<h2>@ViewData["Title"]</h2>

@if (Model.ErrorMessage != null)
{
    <div class="alert alert-danger">@Model.ErrorMessage</div>
}

<div class="row">
    <div class="col-sm-12">
        <section>
            <div class="col-sm-12">
                <p>Cancel the booking and send a message to the passenger. Use this if the booking cannot completed be due to weather, passenger not showing up or similar. Do not use this if the booking is moved to another date.</p>
                <p>The passenger will receive a message on the form: "Unfortunately your flight on @Model.Booking.BookingDate.ToString("dd.MM.yyyy") has been canceled due to {cancel-message}"</p>
                <form asp-controller="BookingAdmin" asp-action="Cancel" method="post" role="form" onsubmit="return submitCancel()">
                    <input type="hidden" name="Id" value="@Model.Booking.Id"/>
                    <div class="form-group">
                        <textarea class="form-control" id="CancelMessage" name="CancelMessage" placeholder="Please enter reason to cancel flight"></textarea>
                    </div>
                    <p>
                        You can uncheck the "send message to passenger" to skip notifying the passenger about the canceled booking. E.g when you are canceling a double booking.
                    </p>
                    <div class="form-group">
                        <div class="checkbox checkbox-inline">
                            <input type="checkbox" name="NotifyPassenger" id="NotifyPassenger" value="true" checked="checked" />
                            <label class="control-label" for="NotifyPassenger">
                                Send message to passenger via SMS
                            </label>
                        </div>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-danger">Cancel Booking</button>
                    </div>
                </form>
            </div>
        </section>
        <div>
            <a href="@Url.Action("Details", new { id = Model.Booking.Id })">Back to Booking Details</a>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        function submitCancel() {
            if ($("#CancelMessage").val() == "") {
                alert("Please enter a message explaining why the flight was canceled");
                return false;
            }

            return confirm("Really cancel the flight?");
        }
    </script>
}

src/Views/BookingAdmin/Complete.cshtml
@using TandemBooking.Services
@model TandemBooking.ViewModels.BookingAdmin.CompleteBookingViewModel
@{
    ViewData["Title"] = "Complete Booking";
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-sm-12">
        <section>
            <div class="col-sm-12">
                <p></p>

                <form asp-controller="BookingAdmin" asp-action="Complete" method="post" role="form" onsubmit="return submitComplete()">
                    <input type="hidden" name="Id" value="@Model.Booking.Id"/>

                    <p>
                        Make sure that passenger fee matches the fee the passenger paid for the flight. Payment should be made to the dedicated pilot account. Either through Vipps or bank transfer by pilot, if the passenger is unable to use Vipps.
                    </p>

                    <div class="form-group">
                        <label asp-for="PassengerFee" class="col-md-2 control-label">Passenger fee</label>
                        <div class="col-md-10">
                            <input asp-for="PassengerFee" class="form-control" />
                            <span asp-validation-for="PassengerFee" class="text-danger" />
                        </div>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Complete Booking</button>
                    </div>
                </form>
            </div>
        </section>
        <div>
            <a href="@Url.Action("Details", new { id = Model.Booking.Id })">Back to Booking Details</a>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        function submitComplete() {
            return confirm("Mark booking as completed?");
        }
    </script>
}

src/Views/BookingAdmin/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@using Microsoft.AspNetCore.Mvc.ViewFeatures
@using TandemBooking.Services
@model TandemBooking.ViewModels.BookingAdmin.EditBookingViewModel

@{
    ViewData["Title"] = "Edit Booking Details";
}

<h2>Edit Booking Details</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="BookingDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <div id="datepicker" class="input-width" data-date='@Model.BookingDate.ToString("MM/dd/yyyy")'></div>
                <input type="hidden" asp-for="BookingDate" class="form-control" />
                <span asp-validation-for="BookingDate" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TimeSlot" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="TimeSlot" class="form-control">
                    @for (int timeslot = 0; timeslot < 5; timeslot++)
                    {
                        <option value="@timeslot">@timeslot.asTime()</option>

                    }
                </select>
                <span asp-validation-for="TimeSlot" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="PassengerName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PassengerName" class="form-control" />
                <span asp-validation-for="PassengerName" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="PassengerWeight" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PassengerWeight" class="form-control" />
                <span asp-validation-for="PassengerWeight" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="PassengerPhone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PassengerPhone" class="form-control" />
                <span asp-validation-for="PassengerPhone" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="PassengerEmail" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PassengerEmail" class="form-control" />
                <span asp-validation-for="PassengerEmail" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="PassengerFee" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="PassengerFee" class="form-control" />
                <span asp-validation-for="PassengerFee" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

<div>
    <a href="@Url.Action("Details", new { id = Model.Id })">Back to Booking Details</a>
</div>

@section scripts
{
    <script>
        $('#datepicker').datepicker({
            format: "mm/dd/yyyy",
            maxViewMode: 2
        });
        $('#datepicker').on("changeDate", function () {
            $('#BookingDate').val(
                $('#datepicker').datepicker('getFormattedDate')
            );
        });
    </script>
}

src/Views/BookingAdmin/Index.cshtml
@using TandemBooking.Services
@model List<Booking>
@{
    ViewData["Title"] = "Booked flights";
}

<h2>@ViewData["Title"]</h2>

<div>
    <ul class="nav navbar-nav">
        <li class=""><a href="@Url.Action("Create")">New Booking</a></li>
        @if (User.IsAdmin())
        {
            <li><a href="@Url.Action("CompletedBookings", "Report")">Completed bookings</a></li>
            <li><a href="@Url.Action("BookingsByPilot", "Report")">Completed bookings per pilot</a></li>
        }
    </ul>
</div>

<table class="table">
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Passenger</th>
        <th>Phone</th>
        <th>Pilot</th>
        <th></th>
    </tr>
    @foreach (var booking in Model)
    {
    <tr class="@(booking.BookingDate < DateTime.Now.Date ? "booking-past" : "") @(booking.Canceled ? "booking-canceled" : "")">
        <td>@booking.BookingDate.ToString("dd.MM.yyyy")</td>
        <td>@booking.TimeSlot.asTime()</td>
        <td>@booking.PassengerName</td>
        <td>@booking.PassengerPhone</td>
        <td>@(booking.AssignedPilot?.Name ?? "No pilot assigned")</td>
        <td><a href="@Url.Action("Details", new { id = booking.Id })" class="btn btn-default">Details</a></td>
    </tr>
    }
</table>